# Important Notes:
# fabric.mod.json's modid field cannot be expanded, you must change it manually.
# Every field you add must be added to the root build.gradle expandProps map.
# Project
version=1.0.1
group=com.github.glowy-players-renewed
java_version=21
# Common
minecraft_version=1.21.1
minecraft_version_range=[1.21.1, 1.22)
## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=1.21.1-20240808.144430
# The version of ParchmentMC that is used, see https://parchmentmc.org/docs/getting-started#choose-a-version for new versions
parchment_minecraft=1.21.1
parchment_version=2024.11.17

# NeoForge
neoforge_version=21.1.80
neoforge_loader_version_range=[4,)

# Fabric
fabric_version=0.109.0+1.21.1
fabric_loader_version=0.16.9

# Mod options
mod_name=Glowy-Players-Renewed
mod_author=JackieJK,HiAndyFan
mod_id=glowyplayers
license=MIT
description=Makes players glow so they can see each other.
home_page=https://github.com/JackieJK/GlowyPlayersRenewed
issue_tracker_url=https://github.com/JackieJK/GlowyPlayersRenewed/issues
# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false


